package app.rigweave.mobile.hamclock

internal enum class HamClockSettingAvailability { ACTIVE, PARTIAL, PLANNED_NOT_AVAILABLE }

/** Production-consumption truth for persisted HamClock settings. */
internal val hamClockSettingAvailability = mapOf(
    "panels" to HamClockSettingAvailability.ACTIVE,
    "panels.id" to HamClockSettingAvailability.ACTIVE,
    "panels.visible" to HamClockSettingAvailability.ACTIVE,
    "panels.order" to HamClockSettingAvailability.ACTIVE,
    "panels.column" to HamClockSettingAvailability.ACTIVE,
    "panels.columnSpan" to HamClockSettingAvailability.ACTIVE,
    "panels.rowSpan" to HamClockSettingAvailability.ACTIVE,
    "panels.collapsed" to HamClockSettingAvailability.ACTIVE,
    "map" to HamClockSettingAvailability.ACTIVE,
    "map.basemap" to HamClockSettingAvailability.ACTIVE,
    "map.followStation" to HamClockSettingAvailability.ACTIVE,
    "map.centerLatitude" to HamClockSettingAvailability.ACTIVE,
    "map.centerLongitude" to HamClockSettingAvailability.ACTIVE,
    "map.zoom" to HamClockSettingAvailability.ACTIVE,
    "map.layers" to HamClockSettingAvailability.ACTIVE,
    "map.layers.id" to HamClockSettingAvailability.ACTIVE,
    "map.layers.visible" to HamClockSettingAvailability.ACTIVE,
    "map.layers.opacity" to HamClockSettingAvailability.ACTIVE,
    "cluster.enabled" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "cluster.windowMinutes" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "cluster.refreshSeconds" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "cluster.maximumSpots" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "cluster.filter" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "pskReporter.enabled" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "pskReporter.direction" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "pskReporter.windowMinutes" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "pskReporter.refreshSeconds" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "pskReporter.maximumReports" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "pskReporter.filter" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "portable.enabledPrograms" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "portable.windowMinutes" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "portable.maximumSpots" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "portable.favouritesOnly" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "portable.showPaths" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "satellites.trackedNoradIds" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "satellites.passWindowHours" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "satellites.minimumElevationDegrees" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "satellites.showTracks" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "satellites.showFootprints" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "satellites.showDoppler" to HamClockSettingAvailability.PLANNED_NOT_AVAILABLE,
    "dxTarget.callsign" to HamClockSettingAvailability.ACTIVE,
    "dxTarget.grid" to HamClockSettingAvailability.ACTIVE,
    "dxTarget.latitude" to HamClockSettingAvailability.ACTIVE,
    "dxTarget.longitude" to HamClockSettingAvailability.ACTIVE,
    "dxTarget.locked" to HamClockSettingAvailability.ACTIVE,
    "dxTarget.source" to HamClockSettingAvailability.ACTIVE,
    "display.density" to HamClockSettingAvailability.ACTIVE,
    "display.timeZoneMode" to HamClockSettingAvailability.ACTIVE,
    "display.hourFormat" to HamClockSettingAvailability.ACTIVE,
    "display.unitSystem" to HamClockSettingAvailability.ACTIVE,
    "display.lowDataMode" to HamClockSettingAvailability.ACTIVE,
    "display.immersive" to HamClockSettingAvailability.ACTIVE,
)
