#include "rigweave/desktop/DesktopPanadapter.hpp"
#include "rigweave/desktop/DesktopPlatform.hpp"
#include "rigweave/desktop/DesktopRadioController.hpp"
#include "rigweave/desktop/DesktopRotatorController.hpp"

#include <QJsonDocument>
#include <QTemporaryDir>
#include <QtTest>
#include <cmath>

using namespace rigweave::desktop;

class DesktopPlatformSafetyTests final : public QObject {
    Q_OBJECT
private slots:
    void credentialFakeUpdatesDeletesWithoutPersistence() { FakeCredentialVault vault;QVERIFY(vault.write("a","label","secret"));QCOMPARE(vault.read("a").value(),QString("secret"));QVERIFY(vault.write("a","label","new"));QCOMPARE(vault.read("a").value(),QString("new"));QVERIFY(vault.remove("a"));QVERIFY(!vault.read("a")); }
    void configurationWhitelistRestoresNoAuthority() { QTemporaryDir dir;DesktopConfigurationManager config(dir.filePath("config.json"));QString error;QVERIFY(config.load(&error));config.setSection("radioProfiles",{{"model",1},{"connected",true},{"ptt",true},{"networkArmed",true},{"pendingCommands",QStringList{"set_freq"}}});config.setSection("wavelogBinding",{{"server","https://example.test"},{"credentialAlias","private"}});QVERIFY(config.exportBundle(dir.filePath("export.json"),&error));QFile file(dir.filePath("export.json"));QVERIFY(file.open(QIODevice::ReadOnly));const QByteArray bytes=file.readAll();QVERIFY(!bytes.contains("credential"));QVERIFY(!bytes.contains("pendingCommands"));QVERIFY(!bytes.contains("connected"));QVERIFY(!bytes.contains("networkArmed"));QVERIFY(!bytes.contains("ptt")); }
    void unknownConfigurationSectionsRequireExplicitReview() { QTemporaryDir dir;DesktopConfigurationManager config(dir.filePath("config.json"));QString error;QVERIFY(config.load(&error));QFile input(dir.filePath("future.json"));QVERIFY(input.open(QIODevice::WriteOnly));input.write("{\"version\":2,\"navigation\":{\"lastDestination\":\"DX\"},\"futureAuthority\":{\"armed\":true}}");input.close();const auto preview=config.previewImport(input.fileName());QVERIFY(preview.value("valid").toBool());QVERIFY(preview.value("requiresReview").toBool());QVERIFY(preview.value("unknownSections").toStringList().contains("futureAuthority"));QVERIFY(!config.applyImport(input.fileName(),{"futureAuthority"},&error));QVERIFY(error.contains("Unknown or unsafe")); }
    void supportBundleCannotRunAfterClose() { DesktopPaths paths;SupportBundle support(&paths);support.close();QString error;QVERIFY(support.create({},&error).isEmpty());QCOMPARE(error,QString("Support bundle service is closed")); }
    void supportBundleRemovesRadioNetworkLocationAndRawStreamData() { QTemporaryDir root;DesktopPaths paths;paths.setEphemeralRoot(root.path());QString error;QVERIFY(paths.create(&error));SupportBundle support(&paths);const QString bundle=support.create({{"radio",QVariantMap{{"hostname","private.example"},{"endpoint","ws://user:pass@192.168.1.22:40001"},{"deviceIdentity","safe-device"},{"callsign","OM0SECRET"},{"configPath","/Users/private/RigWeave/config.json"}}},{"stationLatitude",48.1234},{"stationLongitude",17.1234},{"rawIqSamples","RAW-IQ-MARKER"},{"rawAudioSamples","RAW-AUDIO-MARKER"},{"webSocketPayload","RAW-WS-MARKER"}},&error);QVERIFY2(!bundle.isEmpty(),qPrintable(error));QFile file(bundle);QVERIFY(file.open(QIODevice::ReadOnly));const QByteArray bytes=file.readAll();QVERIFY(!bytes.contains("private.example"));QVERIFY(!bytes.contains("192.168.1.22"));QVERIFY(!bytes.contains("OM0SECRET"));QVERIFY(!bytes.contains("/Users/private"));QVERIFY(!bytes.contains("RAW-IQ-MARKER"));QVERIFY(!bytes.contains("RAW-AUDIO-MARKER"));QVERIFY(!bytes.contains("RAW-WS-MARKER"));QVERIFY(bytes.contains("safe-device")); }
    void radioAndRotatorRestoreSafe() { DesktopRadioController radio;DesktopRotatorController rotator;QCOMPARE(radio.state(),QString("Disconnected"));QVERIFY(!radio.pttAvailable());QVERIFY(!radio.tuneAvailable());QCOMPARE(rotator.state(),QString("Disconnected / automation disarmed"));QVERIFY(!rotator.automationArmed()); }
    void panadapterRejectsMissingRouteAndAcceptsDeterministicStereoTone() { DesktopPanadapter pan;QVERIFY(!pan.start());QByteArray pcm;pcm.resize(96000/10*4);auto*samples=reinterpret_cast<qint16*>(pcm.data());for(int i=0;i<9600;i++){const qint16 value=qint16(std::sin(2.0*3.141592653589793*1000.0*i/96000.0)*12000);samples[2*i]=value;samples[2*i+1]=qint16(std::cos(2.0*3.141592653589793*1000.0*i/96000.0)*12000);}QVERIFY(pan.processPcmForTest(pcm));QVERIFY(!pan.trace().isEmpty());QVERIFY(pan.peakDb()>-80.0); }
    void panadapterMaintainsBoundedIndependentFloatIqContexts() { DesktopPanadapter pan;pan.setWaterfallRows(72);pan.setFftSize(1024);QVector<float> iq(2048);for(int frame=0;frame<1024;++frame){const float phase=float(2.0*3.141592653589793*64.0*frame/1024.0);iq[2*frame]=std::cos(phase)*.4F;iq[2*frame+1]=std::sin(phase)*.4F;}pan.pushFloatIq("tci:0",96000,iq,14074000,false);pan.pushFloatIq("tci:1",48000,iq,7074000,true);QVERIFY(pan.waitForIdleForTest());QCOMPARE(pan.receiverIds().size(),2);pan.setCurrentReceiverId("tci:0");QCOMPARE(pan.renderFrame("tci:0").trace.size(),1024);QCOMPARE(pan.renderFrame("tci:0").waterfall.height(),72);QCOMPARE(pan.frequencyAt(.5,1,0),14074000ULL);const QImage before=pan.renderFrame("tci:0").waterfall;pan.setPaused(true);pan.pushFloatIq("tci:0",96000,iq,14074000,false);QVERIFY(pan.waitForIdleForTest());QCOMPARE(pan.renderFrame("tci:0").waterfall,before);QVERIFY(pan.health().value("pausedDisplay").toBool());QVERIFY(pan.health().value("fftWorker").toBool());QVERIFY(!pan.health().value("captureStopped").toBool());QString error;QVERIFY(!pan.restoreConfiguration({{"schemaVersion",2}},&error));QVERIFY(error.contains("newer")); }
};
QTEST_MAIN(DesktopPlatformSafetyTests)
#include "desktop_platform_safety_tests.moc"
